# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elearning', '0002_auto_20170730_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', utils.models_utils.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', utils.models_utils.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('balance', models.DecimalField(decimal_places=2, default=5, max_digits=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'BankAccounts',
                'verbose_name': 'BankAcount',
            },
        ),
    ]
