# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_remove_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=16),
        ),
    ]
