# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20170729_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
