# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_auto_20170723_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
