# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number_of_minutes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(12)]),
        ),
    ]
