# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-23 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_auto_20170723_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', utils.models_utils.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', utils.models_utils.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='elearning.UserProfile')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
